const felinAddr = [
  {
    address1: '142 BOULEVARD SAINT GERMAIN',
    address2: '',
    alert: null,
    apartment: '',
    area: '',
    areaId: 0,
    areaIdStr: '',
    canDelFlag: true,
    city: 'PARIS',
    cityId: 0,
    cityIdStr: '',
    comment: '',
    country: 'FR',
    countryId: 2612,
    county: null,
    delFlag: 0,
    deliveryAddress: '142 BOULEVARD SAINT GERMAIN',
    addressId: 'feline_config_2021110810081234',
    deliveryAddressId: 'feline_config_2021110810081234',
    deliveryDate: '',
    email: '',
    entrance: '',
    house: '',
    housing: '',
    isDefaltAddress: 0,
    isValidated: null,
    paymentMethods: null,
    pickupCode: null,
    pickupDescription: null,
    pickupName: null,
    pickupPrice: null,
    postCode: '75006',
    province: '',
    provinceCode: null,
    provinceId: null,
    provinceIdStr: '',
    receiveType: 'HOME_DELIVERY',
    rfc: '',
    settlement: null,
    settlementIdStr: '',
    sfccCityCode: null,
    state: null,
    street: '',
    timeSlot: '',
    type: 'DELIVERY',
    validFlag: 1,
    workTime: '',
    firstName: 'Zuo',
    lastName: 'Qin',
    consigneeName: 'Zuo Qin',
    consigneeNumber: '(+33) 4 37 92 70 83'
  }
];

export default felinAddr;
