const felinAddr = [
  {
    address1: 'RUE DE L UNIVERSITE',
    address2: '',
    alert: null,
    apartment: '',
    area: '',
    areaId: null,
    areaIdStr: '',
    canDelFlag: true,
    city: 'PARIS',
    cityId: null,
    cityIdStr: '',
    comment: '',
    consigneeName: 'Xarles Gour',
    consigneeNumber: '(+33) 4 37 92 70 83',
    country: 'FR',
    countryId: 2612,
    county: null,
    createPerson: null,
    createTime: '2021-11-02 01:58:08.000',
    customerId: '8000017ab783085e64f76600da2a6a91',
    delFlag: 0,
    deletePerson: null,
    deleteTime: null,
    deliveryAddress: 'RUE DE L UNIVERSITE',
    deliveryAddressId: '-1',
    deliveryDate: '',
    email: '',
    entrance: '',
    firstName: 'Xarles',
    house: '',
    housing: '',
    isDefaltAddress: 0,
    isValidated: null,
    lastName: 'Gour',
    paymentMethods: null,
    pickupCode: null,
    pickupDescription: null,
    pickupName: null,
    pickupPrice: null,
    postCode: '75007',
    province: '',
    provinceCode: null,
    provinceId: null,
    provinceIdStr: '',
    receiveType: 'HOME_DELIVERY',
    rfc: '',
    settlement: null,
    settlementIdStr: '',
    sfccCityCode: null,
    state: null,
    storeId: 123457909,
    street: '',
    timeSlot: '',
    type: 'DELIVERY',
    updatePerson: null,
    updateTime: null,
    validFlag: 1,
    workTime: ''
  }
];

export default felinAddr;
