import React, { useState, useEffect } from 'react';
import SubGoodsInfos from '../index.js';
import { render } from '@testing-library/react';
import { shallow, mount } from 'enzyme';
const subDetail = {
  subscribeId: 'SRCFRU000003245',
  subscribeStatus: '0',
  customerAccount: 'adat09@yopmail.com',
  customerName: 'Ty Er',
  customerPhone: '+7(435)657-65-87',
  customerType: 'member',
  prescriberId: 'RDW2065382',
  prescriberName: 'ООО "МЕДЗдоровье"',
  petsId: null,
  paymentId: 'PM202207270211151083',
  paymentInfo: null,
  payPaymentInfo: {
    id: '',
    customerId: '800001823796d8c26986a8a7a7417551',
    pspName: 'PAYU',
    paymentItem: 'PAYU_RUSSIA_AUTOSHIP2',
    paymentToken: null,
    lastFourDigits: '5100',
    binNumber: '510510',
    paymentVendor: 'MASTERCARD',
    paymentAccountId: 'fdfd7d0f-ae1e-4303-8c5b-ed7d24d1bbcf',
    expirationDate: '',
    cardCvv: '',
    encryptCardCvv: '',
    cardType: 'CREDIT',
    holderName: 'ada',
    email: '',
    phone: '',
    isDefault: 1,
    delFlag: 0,
    canDelFlag: false,
    storeId: 123457907,
    createTime: '2022-07-27 02:11:16.000',
    updateTime: null,
    accessToken: '',
    showFlag: true,
    paddingFlag: false,
    bindCardLogs: null,
    bindCardRecord: null,
    expireStatusEnum: null
  },
  promotionCode: 'ocj3fbko7070127397',
  petsInfo: null,
  orders: null,
  noStartTradeList: [
    {
      id: null,
      totalTid: null,
      parentId: null,
      groupId: null,
      clinicsId: null,
      prescriberPrimaryKeyId: null,
      clinicsCode: null,
      clinicsName: null,
      buyer: {
        id: '800001823796d8c26986a8a7a7417551',
        name: null,
        account: null,
        email: null,
        levelId: null,
        levelName: null,
        customerFlag: true,
        phone: null,
        employeeId: null,
        firstName: null,
        lastName: null,
        firstNameKatakana: null,
        lastNameKatakana: null,
        customerNameKatakana: null,
        customerNameAtr: null,
        oktaId: null,
        customerDetailId: null,
        externalCustomerId: null,
        externalCustomerNo: null
      },
      seller: null,
      supplier: {
        supplierCode: null,
        supplierName: null,
        supplierId: null,
        storeId: 123457907,
        freightTemplateType: null,
        storeCode: null,
        storeName: null,
        employeeId: null,
        employeeName: null,
        isSelf: null,
        prescriberCode: null,
        currency: null,
        shopperLocale: null,
        currencyValue: null,
        currencyId: null
      },
      buyerRemark: null,
      sellerRemark: null,
      encloses: null,
      requestIp: null,
      invoice: null,
      tradeState: {
        auditState: 'NON_CHECKED',
        flowState: 'INIT',
        payState: 'NOT_PAID',
        pspPayState: 'NOT_PAID',
        deliverStatus: 'NOT_YET_SHIPPED',
        warehouseStatus: null,
        createTime: '2022-12-31 00:00:00.000',
        modifyTime: null,
        endTime: null,
        payTime: null,
        deliverTime: null,
        autoConfirmTime: null,
        startPayTime: null,
        finalTime: null,
        pushTime: null,
        obsoleteReason: null,
        flowStateCode: 1000,
        orderStatus: null,
        invoiceState: null
      },
      consignee: {
        id: '80000182379be1d22a6f8ceca01a601a',
        provinceId: null,
        provinceIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
        cityId: 0,
        cityIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
        areaId: null,
        areaIdStr: null,
        settlementIdStr: null,
        countryId: 1969,
        address: null,
        detailAddress: null,
        detailAddress1: 'Изюмская ул., д. 57, к. 2',
        detailAddress2: null,
        name: null,
        firstName: null,
        lastName: null,
        firstNameKatakana: null,
        lastNameKatakana: null,
        customerNameAtr: null,
        phone: null,
        expectTime: null,
        updateTime: null,
        postCode: '',
        rfc: null,
        email: 'adat09@yopmail.com',
        city: 'Москва',
        sfccCityCode: null,
        sfccCounrtyCode: null,
        country: 'RU',
        province: 'Москва',
        area: null,
        isValidated: null,
        county: null,
        paymentCountry: null,
        street: null,
        settlement: null,
        house: null,
        housing: null,
        entrance: null,
        apartment: null,
        comment: null,
        pickupCode: null,
        deliveryDate: null,
        timeSlot: null,
        workTime: null,
        contractNumber: null,
        courier: null,
        courierCode: null
      },
      tradePrice: {
        serviceFeePrice: null,
        loyaltyPoints: null,
        loyaltyPointsFlag: null,
        loyaltyPointsBefore: null,
        loyaltyPointsEarned: null,
        loyaltyPointsPrice: null,
        goodsPrice: 463,
        deliveryPrice: 400,
        privilegePrice: null,
        discountsPrice: 68.3,
        integral: null,
        integralPrice: null,
        points: null,
        pointsPrice: null,
        pointWorth: null,
        special: false,
        enableDeliveryPrice: false,
        originPrice: 463,
        totalPrice: 794.7,
        totalRegulateDiscount: 0,
        totalPayCash: null,
        practicalPrice: null,
        currency: null,
        rate: null,
        cmCommission: null,
        invoiceFee: null,
        discountsPriceDetails: null,
        couponPrice: 0,
        orderDistributionCommission: 0,
        promotionDiscount: '22.00',
        promotionCodeList: ['ocj3fbko7070127397'],
        promotionDiscountPrice: 22,
        subscriptionDiscountPrice: 46.3,
        taxFeePrice: 0,
        taxFeeRate: 0,
        taxDisplayFlag: false,
        firstOrderOnThePlatformFlag: false,
        firstOrderOnThePlatformDiscountPrice: 0,
        promotionVOList: [
          {
            discountPrice: 22,
            totalGoodsAmount: 416.7,
            skuIds: ['2c91808578c5dc0b0178c9ffae670013'],
            marketingName: '23',
            promotionCode: 'ocj3fbko7070127397',
            marketingType: 0,
            marketingId: 1504,
            couponOrPromotion: 1,
            firstOderOrNormalPromotion: 1,
            isSuperimposeSubscription: 1,
            customProductsType: null,
            publicStatus: '1',
            couponType: null,
            subType: null,
            discount: '22.00'
          }
        ],
        freeShippingFlag: false,
        freeShippingMarketingPromotionVO: null,
        freeShippingDiscountPrice: 0,
        installmentPrice: null,
        totalAddInstallmentPrice: null
      },
      tradeItems: [
        {
          oid: null,
          eoid: null,
          petsId: null,
          petSourceId: null,
          petsName: null,
          petsInfo: null,
          adminId: null,
          storeId: 123457907,
          storeName: null,
          spuId: null,
          spuNo: null,
          externalSkuNo: null,
          skuName: 'Urinary S/O',
          skuNo: '39010040R0',
          spuName: null,
          skuId: '2c91808578c5dc0b0178c9ffae670013',
          eanCode: null,
          goodsWeight: null,
          supplierCode: null,
          goodsWeightUnit: null,
          goodsCubage: null,
          freightTempId: null,
          cateId: null,
          cateName: null,
          isHidden: false,
          goodsCateName: null,
          pic: 'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
          brand: null,
          num: 1,
          deliveredNum: 0,
          deliverStatus: null,
          unit: null,
          price: 394.7,
          regulationDiscount: 0,
          adaptedSubtotalPrice: 394.7,
          originalPrice: 463,
          levelPrice: 0,
          cost: null,
          splitPrice: 0,
          bn: null,
          canReturnNum: null,
          specDetails: '0.4кг',
          specDetailsDaily: null,
          quantityAndRealtimestock: null,
          cateRate: null,
          distributionGoodsAudit: 0,
          distributionCommission: 0,
          commissionRate: null,
          marketingIds: [],
          marketingSettlements: null,
          isAccountStatus: null,
          couponSettlements: [],
          points: null,
          pointsPrice: null,
          pointsGoodsId: null,
          settlementPrice: null,
          isFlashSaleGoods: null,
          flashSaleGoodsId: null,
          enterPriseAuditState: null,
          enterPrisePrice: null,
          subscriptionPrice: 416.7,
          subscriptionStatus: 1,
          goodsCategory: null,
          goodsInfoFlag: 1,
          periodTypeId: 5583,
          recommendationId: 'RDW2065382',
          recommendationBusinessId: null,
          recommendationName: '',
          recommendationType: null,
          recommendationSerialCode: null,
          nextDeliveryTime: '2022-12-31',
          subscriptionDiscountPrice: 46.3,
          loyaltyPointsDiscountPrice: 0,
          loyaltyPointsUnitDiscountPrice: 0,
          promotionDiscountPrice: 22,
          promotionUnitDiscountPrice: 22,
          bundleFlag: null,
          bundleList: null,
          couponCodeDiscountPrice: 0,
          couponCodeUnitDiscountPrice: null,
          prefixFn: null,
          prefixBreed: null,
          utmSource: null,
          utmMedium: null,
          utmCampaign: null,
          referenceData: null,
          referenceId: null,
          referenceObject: null,
          promotionCode: 'ocj3fbko7070127397',
          marketingName: '23',
          subscriptionPlanGiftList: null,
          marketingPromotionVOList: [
            {
              discountPrice: 22,
              totalGoodsAmount: 416.7,
              skuIds: ['2c91808578c5dc0b0178c9ffae670013'],
              marketingName: '23',
              promotionCode: 'ocj3fbko7070127397',
              marketingType: 0,
              marketingId: 1504,
              couponOrPromotion: 1,
              firstOderOrNormalPromotion: 1,
              isSuperimposeSubscription: 1,
              customProductsType: null,
              publicStatus: '1',
              couponType: null,
              subType: null,
              discount: '22.00'
            }
          ],
          petsType: null,
          questionParams: null,
          productCategory: null,
          specialization: null,
          unitOfMeasure: null,
          recommenderName: null,
          recommenderId: null,
          subscriptionSourceList: null,
          goodsMeasureUnit: null,
          unitPrice: 0,
          isSuperimposeSubscription: null,
          promotions: null,
          uom: null,
          factor: null,
          peaweeUseing: null,
          orderLineType: null,
          ration: null,
          externalPrice: null,
          totalAmount: null,
          sentAmount: 0,
          goodsMeasureNum: null,
          goodsInfoBarcode: null,
          eno: null
        }
      ],
      exportTradeItems: null,
      tradeDelivers: [],
      deliverWay: null,
      payInfo: null,
      payOrderId: null,
      platform: null,
      isAuditOpen: true,
      isFirstSubOrder: false,
      paymentOrder: null,
      orderTimeOut: null,
      orderCancelTimeOut: null,
      tradeEventLogs: [],
      channelType: null,
      distributionShareCustomerId: null,
      distributorId: null,
      inviteeId: null,
      shopName: null,
      commission: 0,
      commissionFlag: false,
      distributeItems: [],
      prescriberReward: null,
      firstOrderFlag: null,
      orderRewardRate: null,
      settlementTime: null,
      orderRewardAmount: null,
      segmentNameList: null,
      hasBeanSettled: null,
      canReturnFlag: null,
      refundFlag: null,
      tradeMarketings: null,
      tradeCoupon: null,
      gifts: [],
      subscriptionPlanGiftList: [],
      orderSource: null,
      payWay: null,
      storeBagsFlag: 0,
      distributorName: null,
      canReturnPoints: null,
      canReturnPrice: null,
      orderType: null,
      goodWillFlag: null,
      pointsOrderType: null,
      grouponFlag: false,
      tradeGroupon: null,
      commissions: [],
      totalCommission: 0,
      storeEvaluateVO: null,
      isAutoSub: true,
      subscribeId: null,
      splitOrderFlag: false,
      tidList: null,
      orderCategory: null,
      splitCallBackFlag: true,
      transactionId: null,
      pspName: null,
      paymentItem: 'payu_ru_autoship2',
      paymentItemDisplayName: null,
      paymentVendor: null,
      promotionCode: null,
      orderCreateBy: null,
      subscriptionType: 'Individualization',
      subscriptionTypeQuery: null,
      subscriptionPlanType: null,
      subscriptionRefillType: null,
      toExternalOrderId: null,
      externalSubscribeId: null,
      tradeOms: null,
      sfccSorOrderRefillListID: null,
      orderStatusMap: null,
      maxDeliveryTime: null,
      minDeliveryTime: null,
      paymentMethodNickName: null,
      totalReturnableNumber: null,
      consentIds: null,
      paymentInfoId: null,
      subIdList: null,
      selectWelcomeBoxFlag: null,
      downstreamCount: null,
      appointmentNo: null,
      oldAppointNo: null,
      specialistType: null,
      appointmentTime: null,
      appointmentType: null,
      appointmentDate: null,
      appointmentStatus: null,
      isApptChange: false,
      oldOrderNo: null,
      version: null,
      payPalEmail: null
    }
  ],
  onGoingTradeList: [
    {
      id: 'SITRCFRU000011287',
      totalTid: 'SITRCFRU000011287',
      parentId: 'PO202208050127219866319',
      groupId: null,
      clinicsId: 'RDW2065382',
      prescriberPrimaryKeyId: 'RDW2065382',
      clinicsCode: '',
      clinicsName: 'ООО "МЕДЗдоровье"',
      buyer: {
        id: '800001823796d8c26986a8a7a7417551',
        name: 'Ty Er',
        account: 'adat****.com',
        email: 'adat09@yopmail.com',
        levelId: 234,
        levelName: 'Member',
        customerFlag: true,
        phone: '+7(435)657-65-87',
        employeeId: '2c8080815cd3a74a015cd3ae86850001',
        firstName: 'Ty',
        lastName: 'Er',
        firstNameKatakana: null,
        lastNameKatakana: null,
        customerNameKatakana: 'null null',
        customerNameAtr: 'Ty Er,Er Ty, , ',
        oktaId: '00u4e1dgxwmGaIP7j0x7',
        customerDetailId: null,
        externalCustomerId: null,
        externalCustomerNo: null
      },
      seller: null,
      supplier: {
        supplierCode: 'S00003',
        supplierName: 'Royal Canin_Russain',
        supplierId: 1051,
        storeId: 123457907,
        freightTemplateType: 0,
        storeCode: 'RU',
        storeName: 'Royal Canin Russia',
        employeeId: null,
        employeeName: null,
        isSelf: true,
        prescriberCode: '',
        currency: 'RUB',
        shopperLocale: 'ru_RU',
        currencyValue: null,
        currencyId: null
      },
      buyerRemark: null,
      sellerRemark: null,
      encloses: null,
      requestIp: 'null',
      invoice: {
        orderInvoiceId: null,
        orderInvoiceIdList: null,
        type: 0,
        generalInvoice: {
          flag: 0,
          title: null,
          identification: null
        },
        specialInvoice: null,
        addressId: '80000182379be1d22a6f8ceca01a601a',
        sperator: true,
        address: 'Изюмская ул., д. 57, к. 2',
        address1: 'Изюмская ул., д. 57, к. 2',
        address2: '',
        contacts: 'op po',
        firstName: 'op',
        lastName: 'po',
        phone: '+7(435)657-65-87',
        updateTime: null,
        projectId: '00000000000000000000000000000000',
        projectName: 'Details',
        projectUpdateTime: null,
        countryId: 1969,
        provinceId: null,
        province: 'Москва',
        cityId: 0,
        areaId: 0,
        taxNo: null,
        postCode: '',
        rfc: '',
        email: 'adat09@yopmail.com',
        sfccCityCode: null,
        sfccCountryCode: null,
        city: 'Москва',
        country: 'RU',
        area: null,
        isValidated: null,
        county: null,
        street: '',
        settlement: null,
        house: '',
        housing: '',
        entrance: '',
        apartment: ''
      },
      tradeState: {
        auditState: 'INSIDE_CHECKED',
        flowState: 'PENDING_REVIEW',
        payState: 'AUTHORIZED',
        pspPayState: 'AUTHORIZED',
        deliverStatus: 'NOT_YET_SHIPPED',
        warehouseStatus: null,
        createTime: '2022-08-05 01:27:22.061',
        modifyTime: '2022-08-05 01:27:43.483',
        endTime: null,
        payTime: '2022-08-05 01:27:33.394',
        deliverTime: null,
        autoConfirmTime: null,
        startPayTime: null,
        finalTime: null,
        pushTime: '2022-08-05 01:27:43.481',
        obsoleteReason: null,
        flowStateCode: 2000,
        orderStatus: 'Подтвержден',
        invoiceState: 0
      },
      consignee: {
        id: '80000182379be1d22a6f8ceca01a601a',
        provinceId: null,
        provinceIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
        cityId: 0,
        cityIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
        areaId: 0,
        areaIdStr: null,
        settlementIdStr: null,
        countryId: 1969,
        address: 'Изюмская ул., д. 57, к. 2',
        detailAddress: 'Изюмская ул., д. 57, к. 2',
        detailAddress1: 'Изюмская ул., д. 57, к. 2',
        detailAddress2: '',
        name: 'op po',
        firstName: 'op',
        lastName: 'po',
        firstNameKatakana: null,
        lastNameKatakana: null,
        customerNameAtr: 'Ty Er,Er Ty, , ',
        phone: '+7(435)657-65-87',
        expectTime: null,
        updateTime: null,
        postCode: '',
        rfc: '',
        email: 'adat09@yopmail.com',
        city: 'Москва',
        sfccCityCode: null,
        sfccCounrtyCode: null,
        country: 'RU',
        province: 'Москва',
        area: null,
        isValidated: null,
        county: null,
        paymentCountry: 'RU',
        street: '',
        settlement: null,
        house: '',
        housing: '',
        entrance: '',
        apartment: '',
        comment: '',
        pickupCode: '7701-901',
        deliveryDate: '',
        timeSlot: '',
        workTime: 'Пн-Вс 10:00-21:00',
        contractNumber: null,
        courier: null,
        courierCode: null
      },
      tradePrice: {
        serviceFeePrice: null,
        loyaltyPoints: null,
        loyaltyPointsFlag: null,
        loyaltyPointsBefore: null,
        loyaltyPointsEarned: null,
        loyaltyPointsPrice: null,
        goodsPrice: 463,
        deliveryPrice: 400,
        privilegePrice: null,
        discountsPrice: 68.3,
        integral: null,
        integralPrice: null,
        points: null,
        pointsPrice: null,
        pointWorth: null,
        special: false,
        enableDeliveryPrice: false,
        originPrice: 863,
        totalPrice: 794.7,
        totalRegulateDiscount: 0,
        totalPayCash: null,
        practicalPrice: 794.7,
        currency: null,
        rate: null,
        cmCommission: null,
        invoiceFee: null,
        discountsPriceDetails: null,
        couponPrice: 0,
        orderDistributionCommission: 0,
        promotionDiscount: '22.00',
        promotionCodeList: ['ocj3fbko7070127397'],
        promotionDiscountPrice: 22,
        subscriptionDiscountPrice: 46.3,
        taxFeePrice: 0,
        taxFeeRate: 0,
        taxDisplayFlag: false,
        firstOrderOnThePlatformFlag: false,
        firstOrderOnThePlatformDiscountPrice: 0,
        promotionVOList: [
          {
            discountPrice: 22,
            totalGoodsAmount: 416.7,
            skuIds: ['2c91808578c5dc0b0178c9ffae670013'],
            marketingName: '23',
            promotionCode: 'ocj3fbko7070127397',
            marketingType: 0,
            marketingId: 1504,
            couponOrPromotion: 1,
            firstOderOrNormalPromotion: 1,
            isSuperimposeSubscription: 1,
            customProductsType: null,
            publicStatus: '1',
            couponType: null,
            subType: null,
            discount: '22.00'
          }
        ],
        freeShippingFlag: false,
        freeShippingMarketingPromotionVO: null,
        freeShippingDiscountPrice: 0,
        installmentPrice: null,
        totalAddInstallmentPrice: null
      },
      tradeItems: [
        {
          oid: 'OD202208050127196236850',
          eoid: 'OD202208050127196230511',
          petsId: '',
          petSourceId: null,
          petsName: '',
          petsInfo: null,
          adminId: '1051',
          storeId: 123457907,
          storeName: null,
          spuId: '2c918085773ea33001773eab2914030b',
          spuNo: '3901',
          externalSkuNo: '39010040R0',
          skuName: 'Urinary S/O',
          skuNo: '39010040R0',
          spuName: 'Urinary S/O',
          skuId: '2c91808578c5dc0b0178c9ffae670013',
          eanCode: '4627150232325',
          goodsWeight: 0.4,
          supplierCode: null,
          goodsWeightUnit: 'кг',
          goodsCubage: 1,
          freightTempId: 62,
          cateId: 1159,
          cateName: 'Russia Cat VET Food',
          isHidden: false,
          goodsCateName: 'Cat/Veterinary Health Nutrition/Dry',
          pic: 'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
          brand: 400,
          num: 1,
          deliveredNum: 0,
          deliverStatus: 'NOT_YET_SHIPPED',
          unit: 'UNIT',
          price: 394.7,
          regulationDiscount: 0,
          adaptedSubtotalPrice: 394.7,
          originalPrice: 463,
          levelPrice: 463,
          cost: null,
          splitPrice: 463,
          bn: null,
          canReturnNum: null,
          specDetails: '0.4кг',
          specDetailsDaily: null,
          quantityAndRealtimestock: null,
          cateRate: 20,
          distributionGoodsAudit: 0,
          distributionCommission: 0,
          commissionRate: null,
          marketingIds: [],
          marketingSettlements: null,
          isAccountStatus: null,
          couponSettlements: [],
          points: null,
          pointsPrice: null,
          pointsGoodsId: null,
          settlementPrice: null,
          isFlashSaleGoods: null,
          flashSaleGoodsId: null,
          enterPriseAuditState: null,
          enterPrisePrice: null,
          subscriptionPrice: 416.7,
          subscriptionStatus: 1,
          goodsCategory: null,
          goodsInfoFlag: 1,
          periodTypeId: 5583,
          recommendationId: 'RDW2065382',
          recommendationBusinessId: 'RDW2065382',
          recommendationName: 'ООО "МЕДЗдоровье"',
          recommendationType: null,
          recommendationSerialCode: null,
          nextDeliveryTime: null,
          subscriptionDiscountPrice: 46.3,
          loyaltyPointsDiscountPrice: 0,
          loyaltyPointsUnitDiscountPrice: 0,
          promotionDiscountPrice: 22,
          promotionUnitDiscountPrice: 22,
          bundleFlag: false,
          bundleList: null,
          couponCodeDiscountPrice: 0,
          couponCodeUnitDiscountPrice: null,
          prefixFn: '',
          prefixBreed: '',
          utmSource: '',
          utmMedium: '',
          utmCampaign: '',
          referenceData: '',
          referenceId: '',
          referenceObject: '',
          promotionCode: 'ocj3fbko7070127397',
          marketingName: '23',
          subscriptionPlanGiftList: null,
          marketingPromotionVOList: [
            {
              discountPrice: 22,
              totalGoodsAmount: 416.7,
              skuIds: ['2c91808578c5dc0b0178c9ffae670013'],
              marketingName: '23',
              promotionCode: 'ocj3fbko7070127397',
              marketingType: 0,
              marketingId: 1504,
              couponOrPromotion: 1,
              firstOderOrNormalPromotion: 1,
              isSuperimposeSubscription: 1,
              customProductsType: null,
              publicStatus: '1',
              couponType: null,
              subType: null,
              discount: '22.00'
            }
          ],
          petsType: null,
          questionParams: null,
          productCategory: 'Russia Cat VET Food',
          specialization: '',
          unitOfMeasure: '',
          recommenderName: '',
          recommenderId: '',
          subscriptionSourceList: [
            {
              subscribeId: 'SRCFRU000003245',
              subscribeStatus: '2',
              customerAccount: 'adat09@yopmail.com',
              petsId: null,
              paymentToken: null,
              deliveryTimes: 1,
              deliveryAddressId: '80000182379be1d22a6f8ceca01a601a',
              billingAddressId: '80000182379be1d22a6f8ceca01a601a',
              storeId: 123457907,
              subscriptionType: 'Individualization',
              subscriptionPlanType: null,
              subscribeNum: 1,
              earliestSubscriptionFlag: null
            }
          ],
          goodsMeasureUnit: 'UNIT',
          unitPrice: 0,
          isSuperimposeSubscription: null,
          promotions: 'autoship',
          uom: {
            priceUom: {
              id: '32f0ba821f5811ecaa72a77450361cec',
              code: 'U1721',
              name: 'UNIT',
              ratio: null,
              displayName: null
            },
            stockUom: {
              id: '32f0ba821f5811ecaa72a77450361cec',
              code: 'U1721',
              name: 'UNIT',
              ratio: null,
              displayName: null
            }
          },
          factor: 1,
          peaweeUseing: null,
          orderLineType: 'SUBSCRIPTION',
          ration: '',
          externalPrice: null,
          totalAmount: 1,
          sentAmount: 0,
          goodsMeasureNum: 1,
          goodsInfoBarcode: '4627150232325',
          eno: 1
        }
      ],
      exportTradeItems: null,
      tradeDelivers: [],
      deliverWay: 2,
      payInfo: {
        payTypeId: '0',
        payTypeName: 'ONLINE',
        desc: '在线支付',
        payNumber: 0,
        convenienceStorePayInfo: null,
        twoStages: false,
        mergePay: false
      },
      payOrderId: '8a7082018268e9c401826b9d38cd0002',
      platform: 'CUSTOMER',
      isAuditOpen: false,
      isFirstSubOrder: true,
      paymentOrder: 'PAY_FIRST',
      orderTimeOut: '2022-08-05 01:33:22.068',
      orderCancelTimeOut: null,
      tradeEventLogs: [
        {
          operator: {
            platform: 'PLATFORM',
            name: 'system',
            adminId: null,
            userId: null,
            employeeId: null,
            ip: null,
            storeId: null,
            companyType: null,
            account: null,
            companyInfoId: null,
            services: [],
            requestSource: null
          },
          eventType: 'PENDING_REVIEW',
          eventDetail: '[system]Approved the order by auto',
          eventTime: '2022-08-05 01:27:43.458'
        },
        {
          operator: {
            platform: 'PLATFORM',
            name: 'system',
            adminId: null,
            userId: null,
            employeeId: null,
            ip: null,
            storeId: null,
            companyType: null,
            account: null,
            companyInfoId: null,
            services: [],
            requestSource: null
          },
          eventType: 'AUTHORIZATION',
          eventDetail:
            'Order[SITRCFRU000011287],Request payment, operator:system-SUCCESS',
          eventTime: '2022-08-05 01:27:33.394'
        },
        {
          operator: {
            platform: 'CUSTOMER',
            name: 'Ty er',
            adminId: '',
            userId: '800001823796d8c26986a8a7a7417551',
            employeeId: null,
            ip: 'null',
            storeId: null,
            companyType: null,
            account: 'adat09@yopmail.com',
            companyInfoId: null,
            services: [],
            requestSource: ''
          },
          eventType: 'INIT',
          eventDetail: 'Create Order',
          eventTime: '2022-08-05 01:27:22.068'
        }
      ],
      channelType: null,
      distributionShareCustomerId: null,
      distributorId: null,
      inviteeId: null,
      shopName: null,
      commission: 0,
      commissionFlag: false,
      distributeItems: [],
      prescriberReward: null,
      firstOrderFlag: null,
      orderRewardRate: null,
      settlementTime: null,
      orderRewardAmount: null,
      segmentNameList: null,
      hasBeanSettled: null,
      canReturnFlag: null,
      refundFlag: null,
      tradeMarketings: null,
      tradeCoupon: null,
      gifts: [],
      subscriptionPlanGiftList: [],
      orderSource: 'FGS',
      payWay: null,
      storeBagsFlag: 0,
      distributorName: null,
      canReturnPoints: null,
      canReturnPrice: null,
      orderType: 'SUBSCRIPTION',
      goodWillFlag: 0,
      pointsOrderType: null,
      grouponFlag: false,
      tradeGroupon: null,
      commissions: [],
      totalCommission: 0,
      storeEvaluateVO: null,
      isAutoSub: true,
      subscribeId: 'SRCFRU000003245',
      splitOrderFlag: false,
      tidList: ['SITRCFRU000011287'],
      orderCategory: 'FIRST_AUTOSHIP',
      splitCallBackFlag: true,
      transactionId: null,
      pspName: 'PAYU',
      paymentItem: 'payu_ru_autoship2',
      paymentItemDisplayName: null,
      paymentVendor: null,
      promotionCode: '',
      orderCreateBy: 'PO',
      subscriptionType: 'Individualization',
      subscriptionTypeQuery: 'Autoship',
      subscriptionPlanType: null,
      subscriptionRefillType: 'First',
      toExternalOrderId: 'SITRCFRU000011287',
      externalSubscribeId: null,
      tradeOms: {
        orderId: null,
        orderNo: null,
        customerId: null,
        customerNo: null
      },
      sfccSorOrderRefillListID: null,
      orderStatusMap: null,
      maxDeliveryTime: null,
      minDeliveryTime: null,
      paymentMethodNickName: 'Online payment',
      totalReturnableNumber: null,
      consentIds: null,
      paymentInfoId: 'PM202207270211151083',
      subIdList: ['SRCFRU000003245'],
      selectWelcomeBoxFlag: false,
      downstreamCount: 1,
      appointmentNo: null,
      oldAppointNo: null,
      specialistType: null,
      appointmentTime: null,
      appointmentType: null,
      appointmentDate: null,
      appointmentStatus: null,
      isApptChange: false,
      oldOrderNo: null,
      version: 2,
      payPalEmail: null
    }
  ],
  completedTradeList: [],
  goodsInfo: [
    {
      subscribeGoodsId: 'SD202208050127194011265',
      subscribeId: 'SRCFRU000003245',
      spuId: '2c918085773ea33001773eab2914030b',
      skuId: '2c91808578c5dc0b0178c9ffae670013',
      deliveryTimes: 1,
      spuNo: '3901',
      skuNo: '39010040R0',
      externalSku: null,
      goodsName: 'Urinary S/O',
      goodsPic:
        'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
      stock: 7259,
      subscribePrice: 416.7,
      originalPrice: 463,
      subscribeNum: 1,
      createTime: '2022-08-05 01:27:19.000',
      specText: '0.4кг',
      petsId: null,
      petsName: null,
      goodsInfoFlag: 1,
      periodTypeId: 5583,
      nextDeliveryTime: '2022-12-31',
      recurrentDeliveryTime: '2022-09-16',
      frequency: null,
      goodsSubtitle:
        'Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета.',
      delFlag: false,
      recommendationId: 'RDW2065382',
      recommendationName: '',
      recommendationSerialCode: null,
      goodsInfoVO: {
        goodsInfoId: '2c91808578c5dc0b0178c9ffae670013',
        goodsId: '2c918085773ea33001773eab2914030b',
        goodsInfoName: 'Urinary S/O',
        goodsInfoNo: '39010040R0',
        innerGoodsInfoNo: 'RU_39010040R0',
        goodsInfoImg:
          'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
        goodsInfoBarcode: '4627150232325',
        stock: 7259,
        marketPrice: 463,
        marketPriceExclVat: null,
        supplyPrice: null,
        retailPrice: null,
        grouponPrice: null,
        costPrice: null,
        createTime: '2021-11-09 01:43:47.000',
        updateTime: '2022-08-09 09:06:17.000',
        addedTime: '2021-04-13 11:23:42.000',
        delFlag: 0,
        addedFlag: 1,
        companyInfoId: 1051,
        storeId: 123457907,
        storeName: null,
        customFlag: 0,
        levelDiscountFlag: 0,
        auditStatus: 1,
        companyType: 0,
        aloneFlag: false,
        salePrice: 463,
        priceType: 2,
        mockSpecIds: null,
        mockSpecDetailIds: null,
        specDetailRelIds: null,
        buyCount: 0,
        count: null,
        maxCount: null,
        intervalPriceIds: null,
        specText: '0.4кг',
        intervalMinPrice: null,
        intervalMaxPrice: null,
        validFlag: null,
        cateId: 1159,
        cateName: null,
        isHidden: null,
        brandId: 400,
        storeCateIds: null,
        distributionCommission: null,
        commissionRate: null,
        distributionSalesCount: null,
        distributionGoodsAudit: 0,
        distributionGoodsAuditReason: null,
        checked: false,
        goodsStatus: 0,
        goodsUnit: null,
        marketingLabels: [],
        grouponLabel: null,
        couponLabels: [],
        goodsCubage: 1,
        goodsWeight: 1,
        freightTempId: 62,
        saleType: 0,
        allowPriceSet: null,
        smallProgramCode: null,
        joinDistributior: null,
        goodsEvaluateNum: 3,
        goodsCollectNum: 0,
        goodsSalesNum: 113,
        goodsFavorableCommentNum: 3,
        enterPrisePrice: null,
        enterPriseAuditState: null,
        enterPriseGoodsAuditReason: null,
        subscriptionStatus: 0,
        subscriptionPrice: 416.7,
        linePrice: 0,
        basePrice: 1157.5,
        subscriptionBasePrice: 1041.75,
        basePriceType: '',
        goodsInfoWeight: 0.4,
        goodsInfoUnit: 'кг',
        goods: {
          goodsId: '2c918085773ea33001773eab2914030b',
          cateId: 1159,
          brandId: 400,
          brandName: null,
          goodsName: 'Urinary S/O',
          goodsSubtitle:
            'Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета.',
          goodsNewSubtitle:
            'Уринари С/О: корм сухой, способствующий растворению струвитных мочевых камней и снижению риска их повторного образования',
          goodsDescription: null,
          goodsDescriptionDetails: null,
          goodsNo: '3901',
          innerGoodsNo: 'RU_3901',
          goodsUnit: null,
          goodsCateName: 'Cat/Veterinary Health Nutrition/Dry',
          goodsImg:
            'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
          goodsWeight: 1,
          marketPrice: null,
          supplyPrice: null,
          goodsType: 3,
          costPrice: null,
          createTime: '2021-11-09 01:43:47.000',
          updateTime: '2022-08-09 09:06:17.000',
          addedTime: '2021-11-09 01:43:47.000',
          goodsSource: 1,
          delFlag: 0,
          addedFlag: 1,
          moreSpecFlag: 1,
          priceType: 2,
          customFlag: 0,
          levelDiscountFlag: 0,
          companyInfoId: 1051,
          supplierName: 'Royal Canin_Russain',
          storeId: 123457907,
          storeName: null,
          cateName: null,
          submitTime: '2022-06-13 06:33:27.000',
          auditStatus: 1,
          auditReason: null,
          goodsDetail:
            '[WsContentsDTO(type=Text, title=Text, content=[{"Prescriber Description":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета:<ul><li>способствует растворению струвитных камней в мочевыводящих путях;<li>профилактика образования струвитов и оксалатов кальция. </ul>РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма. Курс применения корма URINARY S/O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного и оксалатного уролитиаза."}, {"EretailShort Description":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета<li>способствует растворению струвитных камней в мочевыводящих путях<li>профилактика образования струвитов и оксалатов кальция<p>Показания:\\n<li>Струвитные уролиты: растворение и профилактика рецидивов\\n\\n<li>Уролиты оксалата кальция: профилактика рецидивов</p>\\n<p>Противопоказания:<p>\\n\\n<li>Хроническая болезнь почек (ХБП)\\n<li>Сердечная недостаточность (с ограничением натрия в диете)\\n\\n<li>Применение лекарственных препаратов, способствующих подкислению мочи\\n<li>Беременность, лактация, рост\\n<p>Urinary S/O – полноценный диетический корм для кошек, способствующий растворению струвитных камней и профилактике их рецидивов благодаря низкому уровню RSS. <p>РЕКОМЕНДАЦИИ. Перед началом диетотерапии проконсультируйтесь с ветеринарным врачом. Струвитные камни растворяются при применении диеты Urinary S/O в течение 5–12 недель. Для предупреждения рецидивов уролитиаза курс лечения следует продолжать еще не менее 6 месяцев. По истечении этого времени необходимо повторное общее обследование, чтобы определить целесообразность диетотерапии на протяжении всей жизни кошки. Убедитесь, что кошке всегда доступна чистая свежая вода.\\n<p>Примечание: при повторяющемся идиопатическом цистите кошек рекомендуется влажный диетический корм Urinary S/O Feline. Перед назначением пожилым животным корма Urinary S/O необходимо убедиться в нормальном функционировании их почек.\\n</p>Масса нетто: 0,4 кг, 1,5 кг, 3,5 кг, 7 кг."}]), WsContentsDTO(type=Text, title=Compositions, content=[{"LEGAL_TEXT_HEADING":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета. "}, {"PARNUTS_STATEMENT":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета:<ul><li>способствует растворению струвитных камней в мочевыводящих путях;<li>профилактика образования струвитов и оксалатов кальция. </ul>РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма. Курс применения корма URINARY S&#x2F;O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного и оксалатного уролитиаза."}, {"COMPOSITION":"Корм сухой полнорационный диетический для кошек URINARY S/O (УРИНАРИ С/О)<p>URINARY S/O – полнорационный диетический корм для кошек.Стимулирует подкисление мочи, а совместно с низким содержанием магния способствует растворению струвитных мочевых камней и снижает риск их повторного образования.Также рекомендуется при воспалении нижних отделов мочевыводящих путей. РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма.Курс применения корма URINARY S/O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного уролитиаза.<p>ИНГРЕДИЕНТЫ: рис, изолят растительных белков*, дегидратированные белки животного происхождения (птица), пшеница, животные жиры, гидролизат белков животного происхождения (вкусоароматические добавки), растительная клетчатка, минеральные вещества, мука из зерновых культур, рыбий жир, соевое масло, фруктоолигосахариды, гидролизат из панциря ракообразных (источник глюкозамина), экстракт бархатцев прямостоячих (источник лютеина). "}, {"ADDITIVES":"ДОБАВКИ (в 1 кг): Питательные добавки: Витамин A: 22000 ME, Витамин D3: 800 ME, Железо: 46 мг, Йод: 3,5 мг, Медь: 8 мг, Марганец: 48 мг, Цинк: 194 мг, Ceлeн: 0,29 мг - Консерванты - Антиокислители."}, {"ANALYTICAL_CONSTITUENTS":"СОДЕРЖАНИЕ ПИТАТЕЛЬНЫХ ВЕЩЕСТВ: Белки: 34,5 % - Жиры: 15 % - Минеральные вещества: 7,4 % - Клетчатка пищевая: 2,1 % - Кальций: 0,8 % - Фосфор: 0,7 % - Натрий: 0,9 % - Магний: 0,05 % - Калий: 1 % - Хлориды: 1,9 % - Сера: 0,5 % - Общий таурин: 0,2 % - Вещества, подкисляющие мочу: кальция сульфат (0,7 %), DL-метионин."}, {"FEEDINGINSTRUCTION":"СПОСОБ УПОТРЕБЛЕНИЯ: Способ употребления: см. таблицу. Корм готов к употреблению. Проследите, чтобы у вашей кошки всегда была свежая вода. Хранить в сухом, прохладном месте. Срок годности: 18 месяцев.<p>Изготовитель: АО «РУСКАН» (ROYAL CANIN Россия), 141870, Россия, Московская обл., Дмитровский г.о., д. Кузяево, д. 70 Бесплатная горячая линия: 8-800-200-37-35.<p>Информация об ингредиентах и нутриентном составе на сайте является справочной. Вся информация о продукте представлена непосредственно на упаковке.</p>"}, {"LIP_STATEMENT":"*L.I.P.: специально отобранные белки с высокой степенью усвояемости."}]), WsContentsDTO(type=Image, title=Benefits, content=[{"Растворение струвитов":{"Description":"Способствует растворению всех типов струвитных камней.","asset_id":89864,"Image":"https://cdn.royalcanin-weshare-online.io/vfrT22gBIYfdNSoC6wqy/v196/vhn-urinary-picto-struvite-dissolution"}}, {"Разбавление мочи":{"Description":"Ненасыщенная моча снижает риск образования струвитных и оксалатных камней.","asset_id":89658,"Image":"https://cdn.royalcanin-weshare-online.io/TGmxzWgBG95Xk-RBA99T/v124/vhn-urinary-picto-urine-dilution"}}, {"Низкий уровень RSS":{"Description":"Снижает концентрацию ионов, участвующих в формировании конкрементов в моче.","asset_id":89846,"Image":"https://cdn.royalcanin-weshare-online.io/WGm_22gBG95Xk-RBwN9K/v238/vhn-urinary-picto-low-rss"}}, {"Низкое содержание магния":{"Description":"Магний является составляющей струвитов (магниево-аммониево-фосфатных солей).","asset_id":89826,"Image":"https://cdn.royalcanin-weshare-online.io/V2m822gBG95Xk-RBVt_c/v80/vhn-urinary-picto-low-magnesium"}}]), WsContentsDTO(type=Image, title=Feeding Guidelines, content=[{"Table":{"Description":"<table><thead><tr><th>Вес кошки</th><th/><th>Упитанность</th><th/></tr></thead><tbody><tr><td/><td>Недостаточный вес</td><td>Нормальный вес</td><td>Избыточный вес</td></tr><tr><td>2 кг</td><td>39 г</td><td>33 г</td><td>26 г</td></tr><tr><td>3 кг</td><td>52 г</td><td>44 г</td><td>35 г</td></tr><tr><td>4 кг</td><td>64 г</td><td>54 г</td><td>43 г</td></tr><tr><td>5 кг</td><td>75 г</td><td>63 г</td><td>50 г</td></tr><tr><td>6 кг</td><td>86 г</td><td>72 г</td><td>57 г</td></tr><tr><td/><td>Смешанное кормление, </td><td>1 пауч urinary S/O + Сухой корм</td><td/></tr><tr><td>Вес кошки</td><td/><td>Упитанность</td><td/></tr><tr><td/><td>Недостаточный вес</td><td>Нормальный вес</td><td>Избыточный вес</td></tr><tr><td>2 кг</td><td>21 г</td><td>14 г</td><td>6 г</td></tr><tr><td>3 кг</td><td>35 г</td><td>26 г</td><td>15 г</td></tr><tr><td>4 кг</td><td>48 г</td><td>37 г</td><td>23 г</td></tr><tr><td>5 кг</td><td>60 г</td><td>47 г</td><td>30 г</td></tr><tr><td>6 кг</td><td>72 г</td><td>57 г</td><td>37 г</td></tr></tbody></table>"}}])]',
          goodsMobileDetail: null,
          stock: null,
          goodsInfoIds: ['2c91808578c5dc0b0178c9ffae670013'],
          storeCateIds: null,
          storeCateNames: null,
          companyType: null,
          goodsCubage: 1,
          freightTempId: 62,
          freightTempName: null,
          saleType: 0,
          goodsVideo: null,
          linePrice: null,
          allowPriceSet: 0,
          goodsEvaluateNum: 3,
          goodsCollectNum: 0,
          goodsSalesNum: 113,
          goodsFavorableCommentNum: 3,
          grouponForbiddenFlag: false,
          subscriptionStatus: 1,
          minMarketPrice: 463,
          minSubscriptionPrice: 1314.9,
          avgEvaluate: null,
          avgEvaluateScore: null,
          baseSpec: null,
          saleableFlag: 1,
          displayFlag: 1,
          weShareId: 271007,
          weightValue: '7',
          goodsStoreCateNames: null,
          productCategoryNames: null,
          defaultPurchaseType: 6899,
          defaultFrequencyId: null,
          resource: 2,
          promotions: 'autoship',
          goodsPillar: null,
          exclusiveFlag: 0,
          wsEnergyCategory: 'normal_outdoor_fcn_breed',
          wsReferenceEnergyValue: 3872,
          wsTechnologyCode: 'dry',
          wsDensity: 360,
          sourceCreateTime: null,
          sourceUpdateTime: '2022-06-08 10:23:17.000',
          serviceTypeId: null,
          assignResources: null,
          isTopPlp: 0
        },
        goodsPromotion: null,
        description: null,
        auditCatFlag: null,
        prescriberFlag: null,
        goodsMeasureNum: 1,
        goodsMeasureUnit: 'UNIT',
        subscriptionDiscountPrice: null,
        goodsInfoFlag: null,
        periodTypeId: null,
        purchasePrice: '100.00000',
        purchasePriceExclVat: null,
        goodsInfoType: null,
        goodsInfoBundleRels: [],
        recommendationId: null,
        recommendationName: null,
        recommendationSerialCode: null,
        weShareScode: 'S27477',
        packSize: '0.4кг',
        subscriptionPercentage: null,
        maxStock: null,
        subscriptionPlanId: null,
        packageId: null,
        subscriptionPlanPromotionFlag: null,
        settingPrice: null,
        virtualInventory: null,
        virtualAlert: null,
        marketingCode: null,
        marketingName: null,
        promotionDiscountPrice: null,
        marketingId: null,
        externalSku: '39010040R0',
        promotions: 'autoship',
        isOfflineStore: null,
        petsId: null,
        petsType: null,
        questionParams: null,
        referenceData: null,
        depth: 1800,
        depthUnit: 'mm',
        width: 1800,
        widthUnit: 'mm',
        height: 1800,
        heightUnit: 'mm',
        specification: null,
        isNotShowCart: null,
        externalStock: 7259,
        externalMarketPrice: 463,
        externalSubscriptionPrice: 416.7,
        externalLinePrice: 0,
        externalPurchasePrice: 100,
        factor: 1,
        stockUomId: '32f0ba821f5811ecaa72a77450361cec',
        priceUomId: '32f0ba821f5811ecaa72a77450361cec',
        priceUom: {
          id: '32f0ba821f5811ecaa72a77450361cec',
          uomCode: 'U1721',
          uomName: 'UNIT',
          categoryId: '2',
          uomCategoryName: null,
          type: 'Reference UOM for this category',
          ratio: null,
          displayName: null,
          status: null,
          storeId: 123457907,
          createTime: null,
          updateTime: null,
          delTime: null,
          delFlag: 0
        },
        stockUom: {
          id: '32f0ba821f5811ecaa72a77450361cec',
          uomCode: 'U1721',
          uomName: 'UNIT',
          categoryId: '2',
          uomCategoryName: null,
          type: 'Reference UOM for this category',
          ratio: null,
          displayName: null,
          status: null,
          storeId: 123457907,
          createTime: null,
          updateTime: null,
          delTime: null,
          delFlag: 0
        },
        defaultSku: null,
        displayOnShop: null,
        productCategory: null,
        cateRate: null
      },
      goodsVO: {
        goodsId: '2c918085773ea33001773eab2914030b',
        cateId: 1159,
        brandId: 400,
        brandName: null,
        goodsName: 'Urinary S/O',
        goodsSubtitle:
          'Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета.',
        goodsNewSubtitle:
          'Уринари С/О: корм сухой, способствующий растворению струвитных мочевых камней и снижению риска их повторного образования',
        goodsDescription: null,
        goodsDescriptionDetails: null,
        goodsNo: '3901',
        innerGoodsNo: 'RU_3901',
        goodsUnit: null,
        goodsCateName: 'Cat/Veterinary Health Nutrition/Dry',
        goodsImg:
          'https://d2cfgssit.z7.web.core.windows.net/RU_271007_master.jpg',
        goodsWeight: 1,
        marketPrice: null,
        supplyPrice: null,
        goodsType: 3,
        costPrice: null,
        createTime: '2021-11-09 01:43:47.000',
        updateTime: '2022-08-09 09:06:17.000',
        addedTime: '2021-11-09 01:43:47.000',
        goodsSource: 1,
        delFlag: 0,
        addedFlag: 1,
        moreSpecFlag: 1,
        priceType: 2,
        customFlag: 0,
        levelDiscountFlag: 0,
        companyInfoId: 1051,
        supplierName: 'Royal Canin_Russain',
        storeId: 123457907,
        storeName: null,
        cateName: null,
        submitTime: '2022-06-13 06:33:27.000',
        auditStatus: 1,
        auditReason: null,
        goodsDetail:
          '[WsContentsDTO(type=Text, title=Text, content=[{"Prescriber Description":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета:<ul><li>способствует растворению струвитных камней в мочевыводящих путях;<li>профилактика образования струвитов и оксалатов кальция. </ul>РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма. Курс применения корма URINARY S/O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного и оксалатного уролитиаза."}, {"EretailShort Description":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета<li>способствует растворению струвитных камней в мочевыводящих путях<li>профилактика образования струвитов и оксалатов кальция<p>Показания:\\n<li>Струвитные уролиты: растворение и профилактика рецидивов\\n\\n<li>Уролиты оксалата кальция: профилактика рецидивов</p>\\n<p>Противопоказания:<p>\\n\\n<li>Хроническая болезнь почек (ХБП)\\n<li>Сердечная недостаточность (с ограничением натрия в диете)\\n\\n<li>Применение лекарственных препаратов, способствующих подкислению мочи\\n<li>Беременность, лактация, рост\\n<p>Urinary S/O – полноценный диетический корм для кошек, способствующий растворению струвитных камней и профилактике их рецидивов благодаря низкому уровню RSS. <p>РЕКОМЕНДАЦИИ. Перед началом диетотерапии проконсультируйтесь с ветеринарным врачом. Струвитные камни растворяются при применении диеты Urinary S/O в течение 5–12 недель. Для предупреждения рецидивов уролитиаза курс лечения следует продолжать еще не менее 6 месяцев. По истечении этого времени необходимо повторное общее обследование, чтобы определить целесообразность диетотерапии на протяжении всей жизни кошки. Убедитесь, что кошке всегда доступна чистая свежая вода.\\n<p>Примечание: при повторяющемся идиопатическом цистите кошек рекомендуется влажный диетический корм Urinary S/O Feline. Перед назначением пожилым животным корма Urinary S/O необходимо убедиться в нормальном функционировании их почек.\\n</p>Масса нетто: 0,4 кг, 1,5 кг, 3,5 кг, 7 кг."}]), WsContentsDTO(type=Text, title=Compositions, content=[{"LEGAL_TEXT_HEADING":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета. "}, {"PARNUTS_STATEMENT":"Корм сухой полнорационный диетический для взрослых кошек, способствующий растворению струвитных камней и предотвращению их повторного образования. Ветеринарная диета:<ul><li>способствует растворению струвитных камней в мочевыводящих путях;<li>профилактика образования струвитов и оксалатов кальция. </ul>РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма. Курс применения корма URINARY S&#x2F;O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного и оксалатного уролитиаза."}, {"COMPOSITION":"Корм сухой полнорационный диетический для кошек URINARY S/O (УРИНАРИ С/О)<p>URINARY S/O – полнорационный диетический корм для кошек.Стимулирует подкисление мочи, а совместно с низким содержанием магния способствует растворению струвитных мочевых камней и снижает риск их повторного образования.Также рекомендуется при воспалении нижних отделов мочевыводящих путей. РЕКОМЕНДАЦИИ: Посоветуйтесь с вашим ветеринарным врачом по поводу целесообразности использования данного корма.Курс применения корма URINARY S/O – от 5 до 12 недель для растворения струвитных камней и до 6 месяцев – в целях снижения риска рецидивов струвитного уролитиаза.<p>ИНГРЕДИЕНТЫ: рис, изолят растительных белков*, дегидратированные белки животного происхождения (птица), пшеница, животные жиры, гидролизат белков животного происхождения (вкусоароматические добавки), растительная клетчатка, минеральные вещества, мука из зерновых культур, рыбий жир, соевое масло, фруктоолигосахариды, гидролизат из панциря ракообразных (источник глюкозамина), экстракт бархатцев прямостоячих (источник лютеина). "}, {"ADDITIVES":"ДОБАВКИ (в 1 кг): Питательные добавки: Витамин A: 22000 ME, Витамин D3: 800 ME, Железо: 46 мг, Йод: 3,5 мг, Медь: 8 мг, Марганец: 48 мг, Цинк: 194 мг, Ceлeн: 0,29 мг - Консерванты - Антиокислители."}, {"ANALYTICAL_CONSTITUENTS":"СОДЕРЖАНИЕ ПИТАТЕЛЬНЫХ ВЕЩЕСТВ: Белки: 34,5 % - Жиры: 15 % - Минеральные вещества: 7,4 % - Клетчатка пищевая: 2,1 % - Кальций: 0,8 % - Фосфор: 0,7 % - Натрий: 0,9 % - Магний: 0,05 % - Калий: 1 % - Хлориды: 1,9 % - Сера: 0,5 % - Общий таурин: 0,2 % - Вещества, подкисляющие мочу: кальция сульфат (0,7 %), DL-метионин."}, {"FEEDINGINSTRUCTION":"СПОСОБ УПОТРЕБЛЕНИЯ: Способ употребления: см. таблицу. Корм готов к употреблению. Проследите, чтобы у вашей кошки всегда была свежая вода. Хранить в сухом, прохладном месте. Срок годности: 18 месяцев.<p>Изготовитель: АО «РУСКАН» (ROYAL CANIN Россия), 141870, Россия, Московская обл., Дмитровский г.о., д. Кузяево, д. 70 Бесплатная горячая линия: 8-800-200-37-35.<p>Информация об ингредиентах и нутриентном составе на сайте является справочной. Вся информация о продукте представлена непосредственно на упаковке.</p>"}, {"LIP_STATEMENT":"*L.I.P.: специально отобранные белки с высокой степенью усвояемости."}]), WsContentsDTO(type=Image, title=Benefits, content=[{"Растворение струвитов":{"Description":"Способствует растворению всех типов струвитных камней.","asset_id":89864,"Image":"https://cdn.royalcanin-weshare-online.io/vfrT22gBIYfdNSoC6wqy/v196/vhn-urinary-picto-struvite-dissolution"}}, {"Разбавление мочи":{"Description":"Ненасыщенная моча снижает риск образования струвитных и оксалатных камней.","asset_id":89658,"Image":"https://cdn.royalcanin-weshare-online.io/TGmxzWgBG95Xk-RBA99T/v124/vhn-urinary-picto-urine-dilution"}}, {"Низкий уровень RSS":{"Description":"Снижает концентрацию ионов, участвующих в формировании конкрементов в моче.","asset_id":89846,"Image":"https://cdn.royalcanin-weshare-online.io/WGm_22gBG95Xk-RBwN9K/v238/vhn-urinary-picto-low-rss"}}, {"Низкое содержание магния":{"Description":"Магний является составляющей струвитов (магниево-аммониево-фосфатных солей).","asset_id":89826,"Image":"https://cdn.royalcanin-weshare-online.io/V2m822gBG95Xk-RBVt_c/v80/vhn-urinary-picto-low-magnesium"}}]), WsContentsDTO(type=Image, title=Feeding Guidelines, content=[{"Table":{"Description":"<table><thead><tr><th>Вес кошки</th><th/><th>Упитанность</th><th/></tr></thead><tbody><tr><td/><td>Недостаточный вес</td><td>Нормальный вес</td><td>Избыточный вес</td></tr><tr><td>2 кг</td><td>39 г</td><td>33 г</td><td>26 г</td></tr><tr><td>3 кг</td><td>52 г</td><td>44 г</td><td>35 г</td></tr><tr><td>4 кг</td><td>64 г</td><td>54 г</td><td>43 г</td></tr><tr><td>5 кг</td><td>75 г</td><td>63 г</td><td>50 г</td></tr><tr><td>6 кг</td><td>86 г</td><td>72 г</td><td>57 г</td></tr><tr><td/><td>Смешанное кормление, </td><td>1 пауч urinary S/O + Сухой корм</td><td/></tr><tr><td>Вес кошки</td><td/><td>Упитанность</td><td/></tr><tr><td/><td>Недостаточный вес</td><td>Нормальный вес</td><td>Избыточный вес</td></tr><tr><td>2 кг</td><td>21 г</td><td>14 г</td><td>6 г</td></tr><tr><td>3 кг</td><td>35 г</td><td>26 г</td><td>15 г</td></tr><tr><td>4 кг</td><td>48 г</td><td>37 г</td><td>23 г</td></tr><tr><td>5 кг</td><td>60 г</td><td>47 г</td><td>30 г</td></tr><tr><td>6 кг</td><td>72 г</td><td>57 г</td><td>37 г</td></tr></tbody></table>"}}])]',
        goodsMobileDetail: null,
        stock: null,
        goodsInfoIds: ['2c91808578c5dc0b0178c9ffae670013'],
        storeCateIds: null,
        storeCateNames: null,
        companyType: null,
        goodsCubage: 1,
        freightTempId: 62,
        freightTempName: null,
        saleType: 0,
        goodsVideo: null,
        linePrice: null,
        allowPriceSet: 0,
        goodsEvaluateNum: 3,
        goodsCollectNum: 0,
        goodsSalesNum: 113,
        goodsFavorableCommentNum: 3,
        grouponForbiddenFlag: false,
        subscriptionStatus: 1,
        minMarketPrice: 463,
        minSubscriptionPrice: 1314.9,
        avgEvaluate: null,
        avgEvaluateScore: null,
        baseSpec: null,
        saleableFlag: 1,
        displayFlag: 1,
        weShareId: 271007,
        weightValue: '7',
        goodsStoreCateNames: null,
        productCategoryNames: null,
        defaultPurchaseType: 6899,
        defaultFrequencyId: null,
        resource: 2,
        promotions: 'autoship',
        goodsPillar: null,
        exclusiveFlag: 0,
        wsEnergyCategory: 'normal_outdoor_fcn_breed',
        wsReferenceEnergyValue: 3872,
        wsTechnologyCode: 'dry',
        wsDensity: 360,
        sourceCreateTime: null,
        sourceUpdateTime: '2022-06-08 10:23:17.000',
        serviceTypeId: null,
        assignResources: null,
        isTopPlp: 0
      },
      signOnSubscriptionFlag: null,
      canCancelPlan: null,
      canChargeDeliveryFlag: null,
      skipNextDeliveryFlag: null,
      cateId: 1159,
      goodsCategory: null,
      inventoryShortageErrorNumber: 0,
      paymentFailureErrorNumber: 0,
      subscriptionPlanGiftList: null,
      notExistStockSubscriptionPlanGiftList: null,
      subscriptionSourceList: null,
      paymentId: null,
      repeatData1: null,
      paymentMethod: null,
      goodsInfos: [
        {
          goodsInfoId: '2c91808578c5dc0b0178c9ffe87200b1',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsInfoName: 'Urinary S/O',
          goodsInfoNo: '39010150R0',
          innerGoodsInfoNo: 'RU_39010150R0',
          goodsInfoImg: null,
          goodsInfoBarcode: '4627150232349',
          stock: 1154,
          marketPrice: 1461,
          marketPriceExclVat: null,
          supplyPrice: null,
          retailPrice: null,
          grouponPrice: null,
          costPrice: null,
          createTime: '2021-11-09 01:43:47.000',
          updateTime: '2022-08-09 09:06:17.000',
          addedTime: '2021-04-13 11:23:42.000',
          delFlag: 0,
          addedFlag: 1,
          companyInfoId: 1051,
          storeId: 123457907,
          storeName: null,
          customFlag: 0,
          levelDiscountFlag: 0,
          auditStatus: 1,
          companyType: 0,
          aloneFlag: false,
          salePrice: 1461,
          priceType: 2,
          mockSpecIds: [669125945],
          mockSpecDetailIds: [480275659],
          specDetailRelIds: null,
          buyCount: 0,
          count: null,
          maxCount: null,
          intervalPriceIds: null,
          specText: null,
          intervalMinPrice: null,
          intervalMaxPrice: null,
          validFlag: null,
          cateId: 1159,
          cateName: null,
          isHidden: null,
          brandId: 400,
          storeCateIds: null,
          distributionCommission: null,
          commissionRate: null,
          distributionSalesCount: null,
          distributionGoodsAudit: 0,
          distributionGoodsAuditReason: null,
          checked: false,
          goodsStatus: 0,
          goodsUnit: null,
          marketingLabels: [],
          grouponLabel: null,
          couponLabels: [],
          goodsCubage: null,
          goodsWeight: null,
          freightTempId: null,
          saleType: 0,
          allowPriceSet: null,
          smallProgramCode: null,
          joinDistributior: null,
          goodsEvaluateNum: null,
          goodsCollectNum: null,
          goodsSalesNum: null,
          goodsFavorableCommentNum: null,
          enterPrisePrice: null,
          enterPriseAuditState: null,
          enterPriseGoodsAuditReason: null,
          subscriptionStatus: 1,
          subscriptionPrice: 1314.9,
          linePrice: 0,
          basePrice: 974,
          subscriptionBasePrice: 876.6,
          basePriceType: '',
          goodsInfoWeight: 1.5,
          goodsInfoUnit: 'кг',
          goods: null,
          goodsPromotion: null,
          description: null,
          auditCatFlag: null,
          prescriberFlag: null,
          goodsMeasureNum: 1,
          goodsMeasureUnit: 'UNIT',
          subscriptionDiscountPrice: null,
          goodsInfoFlag: null,
          periodTypeId: null,
          purchasePrice: '100.00000',
          purchasePriceExclVat: null,
          goodsInfoType: null,
          goodsInfoBundleRels: [],
          recommendationId: null,
          recommendationName: null,
          recommendationSerialCode: null,
          weShareScode: 'S27478',
          packSize: '1.5кг',
          subscriptionPercentage: null,
          maxStock: null,
          subscriptionPlanId: null,
          packageId: null,
          subscriptionPlanPromotionFlag: null,
          settingPrice: null,
          virtualInventory: null,
          virtualAlert: null,
          marketingCode: null,
          marketingName: null,
          promotionDiscountPrice: null,
          marketingId: null,
          externalSku: '39010150R0',
          promotions: 'autoship',
          isOfflineStore: null,
          petsId: null,
          petsType: null,
          questionParams: null,
          referenceData: null,
          depth: 500,
          depthUnit: 'mm',
          width: 500,
          widthUnit: 'mm',
          height: 600,
          heightUnit: 'mm',
          specification: null,
          isNotShowCart: null,
          externalStock: 1154,
          externalMarketPrice: 1461,
          externalSubscriptionPrice: 1314.9,
          externalLinePrice: 0,
          externalPurchasePrice: 100,
          factor: 1,
          stockUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUom: null,
          stockUom: null,
          defaultSku: null,
          displayOnShop: null,
          productCategory: null,
          cateRate: null
        },
        {
          goodsInfoId: '2c91808578c5dc0b0178ca001c1e014b',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsInfoName: 'Urinary S/O',
          goodsInfoNo: '39010350R0',
          innerGoodsInfoNo: 'RU_39010350R0',
          goodsInfoImg: null,
          goodsInfoBarcode: '4627150232363',
          stock: 534,
          marketPrice: 3088,
          marketPriceExclVat: null,
          supplyPrice: null,
          retailPrice: null,
          grouponPrice: null,
          costPrice: null,
          createTime: '2021-11-09 01:43:47.000',
          updateTime: '2022-08-09 09:06:17.000',
          addedTime: '2021-04-13 11:23:42.000',
          delFlag: 0,
          addedFlag: 1,
          companyInfoId: 1051,
          storeId: 123457907,
          storeName: null,
          customFlag: 0,
          levelDiscountFlag: 0,
          auditStatus: 1,
          companyType: 0,
          aloneFlag: false,
          salePrice: 3088,
          priceType: 2,
          mockSpecIds: [669125945],
          mockSpecDetailIds: [267933385],
          specDetailRelIds: null,
          buyCount: 0,
          count: null,
          maxCount: null,
          intervalPriceIds: null,
          specText: null,
          intervalMinPrice: null,
          intervalMaxPrice: null,
          validFlag: null,
          cateId: 1159,
          cateName: null,
          isHidden: null,
          brandId: 400,
          storeCateIds: null,
          distributionCommission: null,
          commissionRate: null,
          distributionSalesCount: null,
          distributionGoodsAudit: 0,
          distributionGoodsAuditReason: null,
          checked: false,
          goodsStatus: 0,
          goodsUnit: null,
          marketingLabels: [],
          grouponLabel: null,
          couponLabels: [],
          goodsCubage: null,
          goodsWeight: null,
          freightTempId: null,
          saleType: 0,
          allowPriceSet: null,
          smallProgramCode: null,
          joinDistributior: null,
          goodsEvaluateNum: null,
          goodsCollectNum: null,
          goodsSalesNum: null,
          goodsFavorableCommentNum: null,
          enterPrisePrice: null,
          enterPriseAuditState: null,
          enterPriseGoodsAuditReason: null,
          subscriptionStatus: 1,
          subscriptionPrice: 2779.2,
          linePrice: 0,
          basePrice: 882.29,
          subscriptionBasePrice: 794.06,
          basePriceType: '',
          goodsInfoWeight: 3.5,
          goodsInfoUnit: 'кг',
          goods: null,
          goodsPromotion: null,
          description: null,
          auditCatFlag: null,
          prescriberFlag: null,
          goodsMeasureNum: 1,
          goodsMeasureUnit: 'UNIT',
          subscriptionDiscountPrice: null,
          goodsInfoFlag: null,
          periodTypeId: null,
          purchasePrice: '100.00000',
          purchasePriceExclVat: null,
          goodsInfoType: null,
          goodsInfoBundleRels: [],
          recommendationId: null,
          recommendationName: null,
          recommendationSerialCode: null,
          weShareScode: 'S27479',
          packSize: '3.5кг',
          subscriptionPercentage: null,
          maxStock: null,
          subscriptionPlanId: null,
          packageId: null,
          subscriptionPlanPromotionFlag: null,
          settingPrice: null,
          virtualInventory: null,
          virtualAlert: null,
          marketingCode: null,
          marketingName: null,
          promotionDiscountPrice: null,
          marketingId: null,
          externalSku: '39010350R0',
          promotions: 'autoship',
          isOfflineStore: null,
          petsId: null,
          petsType: null,
          questionParams: null,
          referenceData: null,
          depth: 0,
          depthUnit: 'mm',
          width: 0,
          widthUnit: 'mm',
          height: 0,
          heightUnit: 'mm',
          specification: null,
          isNotShowCart: null,
          externalStock: 534,
          externalMarketPrice: 3088,
          externalSubscriptionPrice: 2779.2,
          externalLinePrice: 0,
          externalPurchasePrice: 100,
          factor: 1,
          stockUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUom: null,
          stockUom: null,
          defaultSku: null,
          displayOnShop: null,
          productCategory: null,
          cateRate: null
        },
        {
          goodsInfoId: '2c91808578c5dc0b0178ca002c03017c',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsInfoName: 'Urinary S/O',
          goodsInfoNo: '39010700R2',
          innerGoodsInfoNo: 'RU_39010700R2',
          goodsInfoImg: null,
          goodsInfoBarcode: '4627150232387',
          stock: 1222,
          marketPrice: 5712,
          marketPriceExclVat: null,
          supplyPrice: null,
          retailPrice: null,
          grouponPrice: null,
          costPrice: null,
          createTime: '2021-11-09 01:43:47.000',
          updateTime: '2022-08-09 09:06:17.000',
          addedTime: '2021-04-13 11:23:42.000',
          delFlag: 0,
          addedFlag: 1,
          companyInfoId: 1051,
          storeId: 123457907,
          storeName: null,
          customFlag: 0,
          levelDiscountFlag: 0,
          auditStatus: 1,
          companyType: 0,
          aloneFlag: false,
          salePrice: 5712,
          priceType: 2,
          mockSpecIds: [669125945],
          mockSpecDetailIds: [685569249],
          specDetailRelIds: null,
          buyCount: 0,
          count: null,
          maxCount: null,
          intervalPriceIds: null,
          specText: null,
          intervalMinPrice: null,
          intervalMaxPrice: null,
          validFlag: null,
          cateId: 1159,
          cateName: null,
          isHidden: null,
          brandId: 400,
          storeCateIds: null,
          distributionCommission: null,
          commissionRate: null,
          distributionSalesCount: null,
          distributionGoodsAudit: 0,
          distributionGoodsAuditReason: null,
          checked: false,
          goodsStatus: 0,
          goodsUnit: null,
          marketingLabels: [],
          grouponLabel: null,
          couponLabels: [],
          goodsCubage: null,
          goodsWeight: null,
          freightTempId: null,
          saleType: 0,
          allowPriceSet: null,
          smallProgramCode: null,
          joinDistributior: null,
          goodsEvaluateNum: null,
          goodsCollectNum: null,
          goodsSalesNum: null,
          goodsFavorableCommentNum: null,
          enterPrisePrice: null,
          enterPriseAuditState: null,
          enterPriseGoodsAuditReason: null,
          subscriptionStatus: 1,
          subscriptionPrice: 5140.8,
          linePrice: 0,
          basePrice: 816,
          subscriptionBasePrice: 734.4,
          basePriceType: '',
          goodsInfoWeight: 7,
          goodsInfoUnit: 'кг',
          goods: null,
          goodsPromotion: null,
          description: null,
          auditCatFlag: null,
          prescriberFlag: null,
          goodsMeasureNum: 1,
          goodsMeasureUnit: 'UNIT',
          subscriptionDiscountPrice: null,
          goodsInfoFlag: null,
          periodTypeId: null,
          purchasePrice: '100.00000',
          purchasePriceExclVat: null,
          goodsInfoType: null,
          goodsInfoBundleRels: [],
          recommendationId: null,
          recommendationName: null,
          recommendationSerialCode: null,
          weShareScode: 'S27480',
          packSize: '7кг',
          subscriptionPercentage: null,
          maxStock: null,
          subscriptionPlanId: null,
          packageId: null,
          subscriptionPlanPromotionFlag: null,
          settingPrice: null,
          virtualInventory: null,
          virtualAlert: null,
          marketingCode: null,
          marketingName: null,
          promotionDiscountPrice: null,
          marketingId: null,
          externalSku: '39010700R2',
          promotions: 'autoship',
          isOfflineStore: null,
          petsId: null,
          petsType: null,
          questionParams: null,
          referenceData: null,
          depth: 0,
          depthUnit: 'mm',
          width: 0,
          widthUnit: 'mm',
          height: 0,
          heightUnit: 'mm',
          specification: null,
          isNotShowCart: null,
          externalStock: 1222,
          externalMarketPrice: 5712,
          externalSubscriptionPrice: 5140.8,
          externalLinePrice: 0,
          externalPurchasePrice: 100,
          factor: 1,
          stockUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUomId: '32f0ba821f5811ecaa72a77450361cec',
          priceUom: null,
          stockUom: null,
          defaultSku: null,
          displayOnShop: null,
          productCategory: null,
          cateRate: null
        }
      ],
      goodsSpecs: [
        {
          specId: 669125945,
          goodsId: '2c918085773ea33001773eab2914030b',
          specName: 'размер',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: '2022-08-09 09:06:17.000',
          delFlag: 0,
          mockSpecId: 669125945,
          specDetailIds: [267933385, 315401394, 480275659, 685569249],
          editable: null
        }
      ],
      goodsSpecDetails: [
        {
          specDetailId: 267933385,
          goodsId: '2c918085773ea33001773eab2914030b',
          specId: 669125945,
          detailName: '3.5кг',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: '2022-08-09 09:06:17.000',
          delFlag: 0,
          mockSpecId: 669125945,
          mockSpecDetailId: 267933385,
          calculateSort: null,
          editable: null,
          isSelected: null
        },
        {
          specDetailId: 315401394,
          goodsId: '2c918085773ea33001773eab2914030b',
          specId: 669125945,
          detailName: '0.4кг',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: '2022-08-09 09:06:17.000',
          delFlag: 0,
          mockSpecId: 669125945,
          mockSpecDetailId: 315401394,
          calculateSort: null,
          editable: null,
          isSelected: null
        },
        {
          specDetailId: 480275659,
          goodsId: '2c918085773ea33001773eab2914030b',
          specId: 669125945,
          detailName: '1.5кг',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: '2022-08-09 09:06:17.000',
          delFlag: 0,
          mockSpecId: 669125945,
          mockSpecDetailId: 480275659,
          calculateSort: null,
          editable: null,
          isSelected: null
        },
        {
          specDetailId: 685569249,
          goodsId: '2c918085773ea33001773eab2914030b',
          specId: 669125945,
          detailName: '7кг',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: '2022-08-09 09:06:17.000',
          delFlag: 0,
          mockSpecId: 669125945,
          mockSpecDetailId: 685569249,
          calculateSort: null,
          editable: null,
          isSelected: null
        }
      ],
      goodsAttributesValueRelList: [
        {
          id: 'GAR202206130633272280',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210708031540489',
          goodsAttributeValueId: 'AV77097728516050944',
          goodsAttributeName: 'Species',
          goodsAttributeNameEn: 'Species',
          goodsAttributeValue: 'Cat',
          goodsAttributeValueEn: 'Cat',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272281',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210611052632153',
          goodsAttributeValueId: 'AV67346188506411008',
          goodsAttributeName: 'Portfolio Classification',
          goodsAttributeNameEn: 'Portfolio Classification',
          goodsAttributeValue:
            'ROYAL CANIN / VET / Veterinary Health Nutrition',
          goodsAttributeValueEn:
            'ROYAL CANIN / VET / Veterinary Health Nutrition',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR2022061306332722810',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A202101269071242331',
          goodsAttributeValueId: 'AV202101261132238466',
          goodsAttributeName: 'Lifestages',
          goodsAttributeNameEn: 'ВОЗРАСТ',
          goodsAttributeValue: 'Senior_Cat',
          goodsAttributeValueEn: 'Пожилая',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272282',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210204151323718',
          goodsAttributeValueId: 'AV20210204072057d24f',
          goodsAttributeName: 'Pillar',
          goodsAttributeNameEn: 'Pillar',
          goodsAttributeValue: 'VET',
          goodsAttributeValueEn: 'VET',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272283',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210126075253707',
          goodsAttributeValueId: 'AV202101261132240096',
          goodsAttributeName: 'Sterilized',
          goodsAttributeNameEn: 'СТЕРИЛИЗАЦИЯ',
          goodsAttributeValue: 'false',
          goodsAttributeValueEn: 'Нет',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272284',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210126071503738',
          goodsAttributeValueId: 'AV202101261228486286',
          goodsAttributeName: 'Range',
          goodsAttributeNameEn: 'Диапазон',
          goodsAttributeValue: 'Veterinary Health Nutrition_Cat',
          goodsAttributeValueEn: 'Ветеринарное здоровье Питание',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272285',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210126071412517',
          goodsAttributeValueId: 'AV202101261132278466',
          goodsAttributeName: 'Specific needs',
          goodsAttributeNameEn: 'ЛИНЕЙКА',
          goodsAttributeValue: 'Urinary support_Cat',
          goodsAttributeValueEn: 'Поддержка мочевыделительной системы_Кошка',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272286',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210126071341624',
          goodsAttributeValueId: 'AV202101261132240536',
          goodsAttributeName: 'Breeds',
          goodsAttributeNameEn: 'ПОРОДА',
          goodsAttributeValue: 'Cat_Cat',
          goodsAttributeValueEn: 'Метис или беспородная',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272287',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A20210126071322816',
          goodsAttributeValueId: 'AV202101261132251386',
          goodsAttributeName: 'Technology',
          goodsAttributeNameEn: 'Тип корма',
          goodsAttributeValue: 'Dry',
          goodsAttributeValueEn: 'Сухой',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272288',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A202101269071242331',
          goodsAttributeValueId: 'AV202101261132237556',
          goodsAttributeName: 'Lifestages',
          goodsAttributeNameEn: 'ВОЗРАСТ',
          goodsAttributeValue: 'Adult_Cat',
          goodsAttributeValueEn: 'Взрослая',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        },
        {
          id: 'GAR202206130633272289',
          goodsId: '2c918085773ea33001773eab2914030b',
          goodsAttributeId: 'A202101269071242331',
          goodsAttributeValueId: 'AV202101261132238126',
          goodsAttributeName: 'Lifestages',
          goodsAttributeNameEn: 'ВОЗРАСТ',
          goodsAttributeValue: 'Mature_Cat',
          goodsAttributeValueEn: 'Стареющая',
          createTime: '2022-06-13 06:33:27.000',
          updateTime: null,
          delTime: null,
          delFlag: false,
          dataSource: 1
        }
      ]
    }
  ],
  nextDeliveryTime: '2022-12-31',
  deliveryTimes: 1,
  firstDeliveryTime: '2022-08-05',
  deliveryAddressId: '80000182379be1d22a6f8ceca01a601a',
  consignee: {
    deliveryAddressId: '80000182379be1d22a6f8ceca01a601a',
    customerId: '800001823796d8c26986a8a7a7417551',
    consigneeName: 'op po',
    consigneeNumber: '+7(435)657-65-87',
    provinceId: null,
    provinceIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    provinceCode: 'RU-MOW',
    pickupName: 'PickPoint',
    pickupPrice: 300,
    pickupDescription:
      'Постамат расположен в Парикмахерской в здании жилого дома. Транспорт: Автобус №146, 636, С1, С53. Маршрутное такси №Глобус – Изюмская улица, 22. Остановка Улица Изюмская.\nВойти в парикмахерскую HIT Стрижка через центральный вход, на 1 этаже вдоль стены расположен постамат.',
    paymentMethods: 'cod',
    cityId: 0,
    cityIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    city: 'Москва',
    province: 'Москва',
    areaId: 0,
    areaIdStr: null,
    settlementIdStr: null,
    deliveryAddress: 'Изюмская ул., д. 57, к. 2',
    isDefaltAddress: 0,
    delFlag: 0,
    createTime: '2022-07-27 02:10:57.000',
    createPerson: null,
    updateTime: '2022-08-05 01:27:08.000',
    updatePerson: '800001823796d8c26986a8a7a7417551',
    deleteTime: null,
    deletePerson: null,
    countryId: 1969,
    postCode: '',
    rfc: '',
    type: 'DELIVERY',
    address1: 'Изюмская ул., д. 57, к. 2',
    address2: '',
    firstName: 'op',
    lastName: 'po',
    firstNameKatakana: null,
    lastNameKatakana: null,
    canDelFlag: false,
    email: '',
    sfccCityCode: null,
    country: 'RU',
    area: null,
    street: '',
    settlement: null,
    house: '',
    housing: '',
    entrance: '',
    apartment: '',
    isValidated: null,
    storeId: 123457907,
    comment: '',
    receiveType: 'PICK_UP',
    pickupCode: '7701-901',
    deliveryDate: '',
    timeSlot: '',
    workTime: 'Пн-Вс 10:00-21:00',
    validFlag: 1,
    alert: null,
    county: null,
    contractNumber: null,
    courier: null,
    courierCode: null,
    pickupPointState: null
  },
  invoice: {
    deliveryAddressId: '80000182379be1d22a6f8ceca01a601a',
    customerId: '800001823796d8c26986a8a7a7417551',
    consigneeName: 'op po',
    consigneeNumber: '+7(435)657-65-87',
    provinceId: null,
    provinceIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    provinceCode: 'RU-MOW',
    pickupName: 'PickPoint',
    pickupPrice: 300,
    pickupDescription:
      'Постамат расположен в Парикмахерской в здании жилого дома. Транспорт: Автобус №146, 636, С1, С53. Маршрутное такси №Глобус – Изюмская улица, 22. Остановка Улица Изюмская.\nВойти в парикмахерскую HIT Стрижка через центральный вход, на 1 этаже вдоль стены расположен постамат.',
    paymentMethods: 'cod',
    cityId: 0,
    cityIdStr: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
    city: 'Москва',
    province: 'Москва',
    areaId: 0,
    areaIdStr: null,
    settlementIdStr: null,
    deliveryAddress: 'Изюмская ул., д. 57, к. 2',
    isDefaltAddress: 0,
    delFlag: 0,
    createTime: '2022-07-27 02:10:57.000',
    createPerson: null,
    updateTime: '2022-08-05 01:27:08.000',
    updatePerson: '800001823796d8c26986a8a7a7417551',
    deleteTime: null,
    deletePerson: null,
    countryId: 1969,
    postCode: '',
    rfc: '',
    type: 'DELIVERY',
    address1: 'Изюмская ул., д. 57, к. 2',
    address2: '',
    firstName: 'op',
    lastName: 'po',
    firstNameKatakana: null,
    lastNameKatakana: null,
    canDelFlag: false,
    email: '',
    sfccCityCode: null,
    country: 'RU',
    area: null,
    street: '',
    settlement: null,
    house: '',
    housing: '',
    entrance: '',
    apartment: '',
    isValidated: null,
    storeId: 123457907,
    comment: '',
    receiveType: 'PICK_UP',
    pickupCode: '7701-901',
    deliveryDate: '',
    timeSlot: '',
    workTime: 'Пн-Вс 10:00-21:00',
    validFlag: 1,
    alert: null,
    county: null,
    contractNumber: null,
    courier: null,
    courierCode: null,
    pickupPointState: null
  },
  billingAddressId: '80000182379be1d22a6f8ceca01a601a',
  cycleTypeId: null,
  frequency: null,
  storeId: 123457907,
  createTime: '2022-08-05 01:27:19.000',
  updateTime: '2022-08-05 01:27:43.000',
  delTime: null,
  delFlag: false,
  subscriptionPaymentFailFlag: null,
  subscriptionPlanFullFlag: null,
  subscriptionType: 'Individualization',
  externalMainSubscriptionId: null,
  externalSubscribeId: 'SRCFRU000003245',
  petsLifeStageFlag: 0,
  paymentMethod: 'PAYU_RUSSIA_AUTOSHIP2',
  postCodeValidResponse: {
    validFlag: 0,
    alert: 'Sorry we are not able to deliver your order in this area.'
  },
  deliveryDate: null,
  timeSlot: null,
  gifts: null,
  discount: null,
  goodsQuantity: null,
  promotionResponse: {
    totalSubscriptionPrice: 0,
    promotionVOList: [
      {
        id: 83,
        mergeId: '11ad4c5b-19eb-4430-bcc5-865f84482f1a',
        subscriptionId: 'SRCFRU000003245',
        orderId: 'SITRCFRU000011287',
        name: '23',
        value: 22,
        subscriptionDiscount: 46.3,
        discount: '22.00',
        createTime: '2022-08-05 01:27:44.000',
        updateTime: '2022-08-05 01:27:44.000',
        delFlag: 0,
        type: 1,
        useTime: '2022-08-05 01:27:22.000',
        code: 'ocj3fbko7070127397',
        marketingType: 0,
        publicStatus: '1'
      }
    ]
  }
};
console.info('......', JSON.stringify(window.__.env));
window.__.env = { REACT_APP_CURRENCY: 'USD' };
jest.mock('react-slick', () => {
  return {};
});

jest.mock('../HandledSpecSelect', () => () => <div></div>);
jest.mock('./ButtonBoxGift', () => () => <div></div>);
jest.mock('react-intl-phraseapp', () => {
  return {
    injectIntl: () => {},
    FormattedMessage: () => <div></div>
  };
});

jest.mock('configStore', () => {
  return {
    info: () => {}
  };
});

jest.mock('@/utils/utils', () => {
  const originalModule = jest.requireActual('@/utils/utils');

  return {
    __esModule: true,
    ...originalModule,
    getFrequencyDict: () => Promise.resolve({})
  };
});

describe('SubGoodsInfos index', () => {
  it('render test', async () => {
    const wrapper = await render(
      <SubGoodsInfos
        subDetail={subDetail}
        configStore={{ info: { skuLimitThreshold: {} } }}
        getMinDate={(nextDeliveryTime) => {
          return new Date(new Date() + 1 * 24 * 60 * 60 * 1000);
        }}
      />
    );
  });
});
