const PAYMENTAUTHORITY_ENUM = { 1: 'MEMBER', 2: 'MEMBER_AND_VISITOR' };
const ENTERPRICETYPE_ENUM = { 0: 'TAX', 1: 'NO_TAX' };
const PRESCRIBERSELECTTYPED_ENUM = {
  0: 'PRESCRIBER_MAP',
  1: 'RECOMMENDATION_CODE'
};

export {
  PAYMENTAUTHORITY_ENUM,
  ENTERPRICETYPE_ENUM,
  PRESCRIBERSELECTTYPED_ENUM
};
